version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: django_container
    restart: always
    volumes:
      - django_data:/app
    ports:
      - "8000:8000"
      - "80:80"
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: "backend.settings"

volumes:
  django_data:
