{pkgs}: {
  deps = [
    pkgs.libev
    pkgs.iana-etc
    pkgs.xsimd
    pkgs.geos
    pkgs.coreutils
    pkgs.yajl
    pkgs.arrow-cpp
    pkgs.pgadmin4
    pkgs.xcodebuild
    pkgs.libyaml
    pkgs.grpc
    pkgs.c-ares
    pkgs.cacert
    pkgs.bash
    pkgs.util-linux
    pkgs.libffi
    pkgs.gitFull
    pkgs.libsodium
    pkgs.geckodriver
    pkgs.gmp
    pkgs.re2
    pkgs.oneDNN
    pkgs.which
    pkgs.pkg-config
    pkgs.sqlite
    pkgs.postgresql
    pkgs.libuv
    pkgs.rustc
    pkgs.libiconv
    pkgs.cargo
    pkgs.glibcLocales
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.openssl
  ];
}
